import { AppData } from './types';

export const INITIAL_DATA: AppData = {
  students: [
    {
      id: 'std_001',
      name: 'Nguyễn Văn A',
      email: 'vana@example.com',
      phone: '0901234567',
      dob: '2010-05-15',
      parentName: 'Nguyễn Văn C',
      parentPhone: '0901112223',
      goal: 'IELTS 6.5',
      classes: ['cls_001'],
      status: 'active',
      joinedDate: '2023-09-01',
      totalPaid: 5000000,
      balance: 0,
    },
    {
      id: 'std_002',
      name: 'Trần Thị B',
      email: 'thib@example.com',
      phone: '0912345678',
      dob: '2012-10-20',
      parentName: 'Trần Văn D',
      parentPhone: '0912223334',
      goal: 'Giao tiếp cơ bản',
      classes: ['cls_001', 'cls_002'],
      status: 'active',
      joinedDate: '2023-10-15',
      totalPaid: 3000000,
      balance: 1500000,
    },
  ],
  teachers: [
    {
      id: 'tch_001',
      name: 'Mr. Smith',
      email: 'smith@example.com',
      phone: '0987654321',
      specialization: 'IELTS Expert',
      baseSalary: 10000000,
      hourlyRate: 500000,
      kpi: 95,
      status: 'active',
      type: 'full-time',
      color: '#4A90E2',
      avatar: 'https://i.pravatar.cc/150?u=tch_001',
      startDate: '2023-01-01',
    },
  ],
  classes: [
    {
      id: 'cls_001',
      name: 'IELTS Foundation',
      teacherId: 'tch_001',
      schedule: [
        { day: 1, startTime: '18:00', endTime: '20:00', teacherId: 'tch_001' },
        { day: 3, startTime: '18:00', endTime: '20:00', teacherId: 'tch_001' },
      ],
      startDate: '2024-01-01',
      endDate: '2024-06-30',
      tuitionFee: 4500000,
      color: '#4A90E2',
      students: ['std_001', 'std_002'],
      status: 'active',
      type: 'IELTS',
      room: 'Phòng 101',
      syllabus: [
        { week: 1, topic: 'Introduction to IELTS', description: 'Overview of the test format and scoring.' },
        { week: 2, topic: 'Listening Strategies', description: 'Techniques for different question types.' },
        { week: 3, topic: 'Reading Skills', description: 'Skimming and scanning techniques.' },
      ],
    },
    {
      id: 'cls_002',
      name: 'Communication English',
      teacherId: 'tch_001',
      schedule: [
        { day: 5, startTime: '19:00', endTime: '21:00', teacherId: 'tch_001' },
      ],
      startDate: '2024-02-01',
      endDate: '2024-05-30',
      tuitionFee: 3000000,
      color: '#FF9500',
      students: ['std_002'],
      status: 'active',
      type: 'Communication',
      room: 'Phòng 202',
      syllabus: [
        { week: 1, topic: 'Greetings & Introductions', description: 'Basic conversational skills.' },
        { week: 2, topic: 'Daily Routines', description: 'Talking about your day.' },
      ],
    },
  ],
  lessons: [],
  transactions: [
    {
      id: 'txn_001',
      type: 'income',
      amount: 4500000,
      category: 'Học phí',
      description: 'Học phí IELTS Foundation - Nguyễn Văn A',
      date: '2024-01-05',
      relatedId: 'std_001',
    },
  ],
  settings: {
    currency: 'VND',
    theme: 'light',
    centerName: 'Anh Ngữ Ms. Thương',
    aiModel: 'gemini-3-flash-preview',
  },
};
